apis/brand-api/docker-compose.yaml
common/scripts/docker-build.sh
common/scripts/docker-up.sh

Changed some scripts path.
Changed PostgreSQL version to 13, so that will use the latest 13 version.

Changed scripts path, and changed PostgreSQL version to 13

---

.ci/docker-compose.yml
docker-compose.yaml

This PR was mainlly to test pre-commit git hook in my system.
Worked! :-)

Give names to docker containers, and this commit is to test pre-commit

---

.pre-commit-config.yaml
apis/brand_api/Dockerfile

Added no-commit-to-branch to the pre-commit.

Added comments to Dockerfile, and arranged the ENV.

---

apis/brand_api/crud.py
apis/brand_api/db/models.py
apis/brand_api/main.py
apis/brand_api/schemas.py
apis/brand_api/tests/test_categories.py

Added route for getting and posting categories

Added post and get categories

---

Todo.md

Updated TODO about category patch.

---

apis/brand_api/crud.py

Improved some typing in crud.

---

apis/brand_api/schemas.py
apis/brand_api/tests/test_categories.py

Bug. Internal error if price value was wrong. Now it validates against schema.

Wrong category price got internal error. Made a validation and a test.

---

Makefile
Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/schemas.py
apis/brand_api/tests/test_app.py
apis/brand_api/tests/test_brand.py
apis/brand_api/tests/test_categories.py
apis/brand_api/tests/test_user.py
docker-compose.yaml

Changed tests to be unit instead of integration, adjusted docker and tests marks
Isort now enabled to fix and not just check
Updated todo list
Added route to delete brand
Updated some types in the schemas

Added route to delete brand

---

.github/labeler.yml
Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/tests/test_user.py

Added the delete user. Needed to remake the read_user function.

---

apis/brand_api/tests/test_categories.py
apis/brand_api/tests/test_user.py

Removed passing dependencies on user and categories that were not being used

Removed dependencies in tests that were not needed;

---

Todo.md

Added one task to the todo list

Update to todo

---

.github/labeler.yml
.github/pr-labeler.yml
.github/workflows/brand_microservices_ci.yml

Changed from labeler to pr-labeler.

---

Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/schemas.py
apis/brand_api/tests/test_user.py

Added route to update password of user

feature: added patch user route

---

Todo.md

Updated todo

---

README.md

Give some color to the readme.

---

Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/schemas.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_categories.py

- Adds timestamp and ownership to all routes in category and categories.

feat: timestamp and ownership to category

---

Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/schemas.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_brand.py

Removed the route endpoint from the docs
Added timestamps and ownership to brands

feat: added timestamps and ownership to brands

---

Todo.md
apis/brand_api/crud.py
apis/brand_api/db/models.py
apis/brand_api/main.py
apis/brand_api/schemas.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_user.py

Added timestamp and ownership to users

feat: timestamp and ownership of users

---

Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/schemas.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_brand.py
apis/brand_api/tests/test_categories.py
apis/brand_api/tests/test_user.py

New response for brands which is now a dictionary with brands key and a list of brands
Refactored the tests so that timestamp and ownership are running on a single function for all tests
We need to look into the potential of changing the function to a class on the conftest with methods for timestamp and ownership

feat: new dict response with a list of brands

---

.github/workflows/brand_cd.yml
.github/workflows/brand_ci.yml

added deploy yml

---

.github/workflows/brand_cd.yml
.github/workflows/brand_ci.yml

added deploy yml (#50)

---

.github/workflows/brand_cd.yml
Makefile

Added a new arg in make for the deployment.

---

Todo.md
apis/brand_api/tests/test_brand.py
apis/brand_api/tests/test_categories.py
apis/brand_api/tests/test_user.py
pyproject.toml

Updated a few dependencies most importantly fastapi to version 0.92
Updated todo list

feat: update dependencies

---

.github/workflows/pr_limit.yml

Moved pr_limit to workflow.

---

Todo.md
apis/brand_api/main.py
apis/brand_api/tests/test_user.py

Fixed bug in POST Login

---

Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/tests/test_categories.py

Added the ability to read one category by passing the id as param

feat: ability to read one category

---

Todo.md
apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/tests/test_categories.py
apis/brand_api/tests/test_user.py

Ability to read only one user by it's id

feat: ability to read one user

---

Makefile
apis/brand_api/Dockerfile
docker-compose.yaml
pyproject.toml

Production ready.

---

.github/workflows/brand_cd.yml

Deploy to production.

---

docker-compose.yaml

Database url for production was incorrect

fix: database url

---

.github/workflows/brand_cd.yml
.github/workflows/brand_ci.yml
docker-compose.yaml

Added volumes to the database with an init to sort permissions
Added .env to the exclude in ssh deployment

fix: database docker issues

---

docker-compose.yaml

Changed docker compose to fix volumes in production.

Changed docker compose to fix volumes in production.

---

Makefile
docker-compose.yaml
traefik.dev.toml

Added traefik service to docker compose

feat: https

---

.github/workflows/brand_cd.yml

feat-ignore traefik folder on cd

---

README.md
apis/brand_api/main.py

Completed the README file
Added some description to OpenAPI and a warning about data deletion

doc: Completed readme and add some description for OpenAPI

---

apis/brand_api/dependencies.py
apis/brand_api/main.py
apis/brand_api/routers/brands.py
apis/brand_api/routers/categories.py
apis/brand_api/routers/users.py
apis/brand_api/schemas.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_user.py

Added validation to users and improved further on the schemas

feat: added validation to users

---

apis/brand_api/crud.py
apis/brand_api/main.py
apis/brand_api/routers/brands.py
apis/brand_api/schemas.py
apis/brand_api/tests/test_brand.py
pyproject.toml

Added validation to brands
Upped the version

feat: added validation to brands

---

apis/brand_api/crud.py
apis/brand_api/dependencies.py
apis/brand_api/main.py
apis/brand_api/routers/brands.py
apis/brand_api/routers/categories.py
apis/brand_api/routers/users.py
apis/brand_api/schemas.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_brand.py
apis/brand_api/tests/test_user.py
pyproject.toml

release: 0.2.0

---

apis/brand_api/crud.py
apis/brand_api/routers/users.py
apis/brand_api/schemas.py
pyproject.toml

Changed schemas to have a base configuration
Added defaults to deleted_by and updated_by on users
Changed the crud for users

fix schemas and response for users

---

apis/brand_api/crud.py
apis/brand_api/routers/users.py
apis/brand_api/schemas.py
pyproject.toml

release v0.3.1

---

.github/workflows/brand_cd.yml

It enables automatic writing of the version to myproject.toml, from the tag.

Added to CI write the version to myproject

---

.github/workflows/brand_cd.yml

changed myproject to pyproject

---

.github/workflows/brand_cd.yml
README.md
apis/brand_api/main.py
apis/brand_api/routers/users.py
apis/brand_api/schemas.py
docker-compose.yaml

…tation
Introduced the use of a trial user for development and production
Testing continues to do the same
Changed the CD to only trigger on new releases

fix: introduced a trial user

---

pyproject.toml

fix: fixed test errors by rebuilding container. updated toml syntax

---

.github/workflows/brand_cd.yml
README.md
pyproject.toml

Updated readme regarding the use of pyenv to manage versions of python
Removed the toml version from CD as it is not currently working as intended

refactor: updated readme. removed toml version update from cd

---

Makefile
apis/brand_api/crud.py
apis/brand_api/db/models.py
apis/brand_api/main.py
apis/brand_api/routers/brand_id_socials.py
apis/brand_api/routers/brands.py
apis/brand_api/routers/socials.py
apis/brand_api/schemas.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_brand.py
apis/brand_api/tests/test_brand_socials.py
apis/brand_api/tests/test_categories.py
apis/brand_api/tests/test_socials.py
pyproject.toml

Added endpoint for posting and reading social networks
Added endpoints to associate a social network to a brand through their ids

feature: new social endpoints

---

apis/brand_api/db/models.py
pyproject.toml

Fixed bug on timestamp for created at using model generation timestam instead of current time

fix: fixed bug on timestamps

---

apis/brand_api/crud.py
apis/brand_api/routers/brands.py
apis/brand_api/routers/categories.py
apis/brand_api/routers/users.py
apis/brand_api/tests/conftest.py
apis/brand_api/tests/test_brand.py
apis/brand_api/tests/test_categories.py
apis/brand_api/tests/test_user.py
pyproject.toml

…rands
Added order by on get all routes
Added asc and desc directions
Added category id query to brands
Spotted a bug with created at as it is taking the session date and not real time date

feat: added order by and sorting direction

---

apis/brand_api/routers/brand_id_socials.py
apis/brand_api/routers/brands.py
apis/brand_api/routers/categories.py
apis/brand_api/routers/socials.py
apis/brand_api/routers/users.py
apis/brand_api/schemas.py
pyproject.toml

Added more info to params, queries and actions on openapi
Added error models to openapi
Updated a few items that were incorrect

feat: updated openapi on queries, params and headers. added error models
